
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      - PORT=${PORT}
      - AUTH_API_ADDRESS=${AUTH_API_ADDRESS}
      - TODOS_API_ADDRESS=${TODOS_API_ADDRESS}
    ports:
      - "8080:8080"
    depends_on:
      - auth-api
      - todos-api
      - users-api
    networks:
      - redis-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`paul.tech`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "traefik.http.services.frontend.loadbalancer.server.port=8080"

      

  auth-api:
    build:
      context: ./auth-api
      dockerfile: Dockerfile
    container_name: auth-api
    environment:
      - AUTH_API_PORT=${AUTH_API_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - USERS_API_ADDRESS=${USERS_API_ADDRESS}
    ports:
      - "8081:8081"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth-api-domain.rule=Host(`auth.paul.tech`)"
      - "traefik.http.routers.auth-api-domain.entrypoints=websecure"
      - "traefik.http.routers.auth-api-domain.tls=true"
      - "traefik.http.routers.auth-api-domain.tls.certresolver=myresolver"
      - "traefik.http.services.auth-api.loadbalancer.server.port=8081"
    depends_on:
      - redis-queue
    networks:
      - redis-network

  todos-api:
    build:
      context: ./todos-api
      dockerfile: Dockerfile
    container_name: todos-api
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_CHANNEL=${REDIS_CHANNEL}
    ports:
      - "8082:8082"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.todos-api-domain.rule=Host(`todos.paul.tech`)"
      - "traefik.http.routers.todos-api-domain.entrypoints=websecure"
      - "traefik.http.routers.todos-api-domain.tls=true"
      - "traefik.http.routers.todos-api-domain.tls.certresolver=myresolver"
      - "traefik.http.services.todos-api.loadbalancer.server.port=8082"
    depends_on:
      - redis-queue
    networks:
      - redis-network 

  users-api:
    build:
      context: ./users-api
      dockerfile: Dockerfile
    container_name: users-api
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "8083:8083"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.users-api-domain.rule=Host(`users.paul.tech`)"
      - "traefik.http.routers.users-api-domain.entrypoints=websecure"
      - "traefik.http.routers.users-api-domain.tls=true"
      - "traefik.http.routers.users-api-domain.tls.certresolver=myresolver"
      - "traefik.http.services.users-api.loadbalancer.server.port=8083"
    depends_on:
      - redis-queue
    networks:
      - redis-network

  log-message-processor:
    build:
      context: ./log-message-processor
      dockerfile: Dockerfile
    container_name: log-message-processor
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_CHANNEL=${REDIS_CHANNEL}
    depends_on:
      - redis-queue
    networks:
      - redis-network

  redis-queue:
    image: redis:latest
    container_name: redis-queue
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - redis-network
    labels:
      - "traefik.enable=false"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3



  traefik:
    image: traefik:v2.6
    container_name: traefik
    command:             
      - --api.insecure=true
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --providers.file.directory=/etc/traefik/config
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.dashboard.address=:8087
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entryPoint.permanent=true
      # Let's Encrypt configuration
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --certificatesresolvers.myresolver.acme.email=arinzennajipaul@gmail.com
      - --certificatesresolvers.myresolver.acme.storage=/etc/traefik/acme/acme.json
      - --log.level=INFO

    ports:
      - 80:80
      - 443:443
      - 8087:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/config:/etc/traefik
      - ./traefik/acme:/etc/traefik/acme
    networks:
      - redis-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(traefik.paul.tech)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=dashboard"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$ruca84Hq$$mbjdMZBAG.KWn7vfN/SNK/"  # admin:password
    restart: unless-stopped

networks:
  redis-network:
    driver: bridge

volumes:
  redis_data: